apiVersion: v1
kind: Secret
metadata:
  name: argo-webhook-url
  namespace: argocd
type: Opaque
stringData:
  url: "https://argocd-vcp.demo.vcluster.dev/api/webhook"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-appset-webhook-url
  namespace: argocd
type: Opaque
stringData:
  url: "https://argocd-appset-vcp.demo.vcluster.dev/api/webhook"
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-url
  namespace: p-auth-core
type: Opaque
stringData:
  url: "https://flux-webhook-vcp.demo.vcluster.dev/hook/97184ed7cbe13e33d4548c249d31f957b6af9b47fc2227a682936b3b352cf932"
